# Generated by Django 6.0.4 on 2026-05-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('patient', 'Пацієнт'), ('doctor', 'Лікар'), ('admin', 'Адміністратор')], default='patient', max_length=20)),
            ],
        ),
    ]
