# Generated by Django 6.0.4 on 2026-05-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, max_length=50)),
                ('well_being', models.CharField(blank=True, max_length=50)),
                ('temperature', models.FloatField(default=36.6)),
                ('pressure', models.CharField(blank=True, max_length=20)),
                ('complaints', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('medicines', models.ManyToManyField(blank=True, related_name='records', to='diary.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='diary.userprofile')),
            ],
        ),
    ]
