# Generated by Django 6.0.4 on 2026-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_healthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
