# Generated by Django 6.0.4 on 2026-05-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_healthrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='Спеціальність')),
                ('year_of_experience', models.PositiveIntegerField(default=0, verbose_name='Стаж роботи')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='diary.userprofile')),
            ],
        ),
    ]
