# Generated by Django 6.0.4 on 2026-05-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='diary.userprofile'),
        ),
    ]
