# Generated by Django 6.0.4 on 2026-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
