# Generated by Django 6.0.4 on 2026-08-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_remove_question_email_remove_question_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='blood_sugar',
            field=models.FloatField(blank=True, help_text='Рівень цукру в крові (ммоль/л)', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Калорії за день', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Рівень енергії (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Пульс (удари за хвилину)', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='mood',
            field=models.CharField(blank=True, choices=[('great', 'Чудово'), ('good', 'Добре'), ('okay', 'Нормально'), ('bad', 'Погано'), ('terrible', 'Жахливо')], help_text='Настрій', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='pain_level',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Рівень болю (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Сон за ніч (години)', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='steps',
            field=models.IntegerField(blank=True, help_text='Кількість кроків за день', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='water_intake',
            field=models.IntegerField(blank=True, help_text='Вода (мл за день)', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вага (кг)', null=True),
        ),
    ]
