# Generated by Django 6.0.4 on 2026-08-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_healthrecord_blood_sugar_healthrecord_calories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-date'], 'verbose_name': "Запис здоров'я", 'verbose_name_plural': "Записи здоров'я"},
        ),
    ]
