# Generated by Django 6.0.4 on 2026-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_healthrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='Сатурація (SpO2) %', null=True),
        ),
    ]
