# Generated by Django 6.0.4 on 2026-09-19 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_healthrecord_spo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='pressure',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Артеріальний тиск (діастолічний) мм рт.ст.', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Артеріальний тиск (систолічний) мм рт.ст.', null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_sugar',
            field=models.FloatField(blank=True, help_text='Рівень цукру (ммоль/л)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(30.0)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Калорії за день', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Пульс (уд/хв)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Сон за ніч (години)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='Сатурація (SpO2) %', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='steps',
            field=models.IntegerField(blank=True, help_text='Кількість кроків за день', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='temperature',
            field=models.FloatField(default=36.6, help_text='Температура (°C)', validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='water_intake',
            field=models.IntegerField(blank=True, help_text='Вода (мл за день)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вага (кг)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
