# Generated by Django 6.0.4 on 2026-09-19 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_remove_healthrecord_medicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_sugar',
            field=models.FloatField(blank=True, help_text='Рівень цукру (ммоль/л)', null=True, validators=[django.core.validators.MinValueValidator(1.0, message='Рівень цукру має бути від 1.0 до 30.0 ммоль/л'), django.core.validators.MaxValueValidator(30.0, message='Рівень цукру має бути від 1.0 до 30.0 ммоль/л')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Калорії за день', null=True, validators=[django.core.validators.MinValueValidator(0, message='Калорії мають бути від 0 до 10000 ккал'), django.core.validators.MaxValueValidator(10000, message='Калорії мають бути від 0 до 10000 ккал')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Пульс (уд/хв)', null=True, validators=[django.core.validators.MinValueValidator(30, message='Пульс має бути від 30 до 250 уд/хв'), django.core.validators.MaxValueValidator(250, message='Пульс має бути від 30 до 250 уд/хв')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Артеріальний тиск (діастолічний) мм рт.ст.', null=True, validators=[django.core.validators.MinValueValidator(40, message='Діастолічний тиск має бути від 40 до 150 мм рт.ст.'), django.core.validators.MaxValueValidator(150, message='Діастолічний тиск має бути від 40 до 150 мм рт.ст.')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Артеріальний тиск (систолічний) мм рт.ст.', null=True, validators=[django.core.validators.MinValueValidator(60, message='Систолічний тиск має бути від 60 до 250 мм рт.ст.'), django.core.validators.MaxValueValidator(250, message='Систолічний тиск має бути від 60 до 250 мм рт.ст.')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Сон за ніч (години)', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Сон має бути від 0 до 24 годин'), django.core.validators.MaxValueValidator(24.0, message='Сон має бути від 0 до 24 годин')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='Сатурація (SpO2) %', null=True, validators=[django.core.validators.MinValueValidator(50, message='Сатурація має бути від 50 до 100%'), django.core.validators.MaxValueValidator(100, message='Сатурація має бути від 50 до 100%')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='steps',
            field=models.IntegerField(blank=True, help_text='Кількість кроків за день', null=True, validators=[django.core.validators.MinValueValidator(0, message='Кроки мають бути від 0 до 100000'), django.core.validators.MaxValueValidator(100000, message='Кроки мають бути від 0 до 100000')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Температура (°C)', null=True, validators=[django.core.validators.MinValueValidator(30.0, message='Температура має бути від 30.0 до 45.0 °C'), django.core.validators.MaxValueValidator(45.0, message='Температура має бути від 30.0 до 45.0 °C')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='water_intake',
            field=models.IntegerField(blank=True, help_text='Вода (мл за день)', null=True, validators=[django.core.validators.MinValueValidator(0, message='Вода має бути від 0 до 10000 мл'), django.core.validators.MaxValueValidator(10000, message='Вода має бути від 0 до 10000 мл')]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вага (кг)', null=True, validators=[django.core.validators.MinValueValidator(1.0, message='Вага має бути від 1.0 до 300.0 кг'), django.core.validators.MaxValueValidator(300.0, message='Вага має бути від 1.0 до 300.0 кг')]),
        ),
    ]
