# Generated by Django 6.0.4 on 2026-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_alter_healthrecord_blood_sugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
