# Generated by Django 6.0.4 on 2026-09-19 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введіть коректний номер телефону', regex='^\\+?[\\d\\s\\-\\(\\)]{10,20}$')]),
        ),
    ]
