# Generated by Django 6.0.4 on 2026-09-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0020_schedule_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
    ]
