# Generated by Django 6.0.4 on 2026-09-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_appointment_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
