# Generated by Django 6.0.4 on 2026-09-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0024_auto_20260922_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date'], 'verbose_name': 'Прийом', 'verbose_name_plural': 'Прийоми'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Активний'), ('completed', 'Завершений'), ('cancelled', 'Скасовано')], default='scheduled', max_length=20),
        ),
    ]
