# Generated by Django 6.0.4 on 2026-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0025_alter_appointment_options_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклади'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default='2026-01-01', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot_duration',
            field=models.IntegerField(default=30, verbose_name='Тривалість прийому (хв)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Початок'),
        ),
    ]
