# Generated by Django 6.0.4 on 2026-09-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0026_alter_schedule_options_remove_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
