# Generated by Django 6.0.4 on 2026-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0028_alter_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_day_off',
            field=models.BooleanField(default=False, verbose_name='Вихідний'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок'),
        ),
    ]
