# Generated by Django 6.0.4 on 2026-09-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0029_schedule_is_day_off_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Відповідь лікаря'),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_questions', to='diary.userprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('answered', 'Відповідь надано'), ('closed', 'Закрито')], default='new', max_length=20),
        ),
    ]
