# Generated by Django 6.0.4 on 2026-09-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0031_questionmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='doctor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_questions', to='diary.userprofile', verbose_name='Лікар'),
            preserve_default=False,
        ),
    ]
