# Generated by Django 6.0.4 on 2026-09-23 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0032_alter_question_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Діагноз')),
                ('prescriptions', models.TextField(verbose_name='Призначення')),
                ('recommendations', models.TextField(verbose_name='Рекомендації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='diary.appointment', verbose_name='Прийом')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='diary.userprofile', verbose_name='Лікар')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_conclusions', to='diary.userprofile', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Висновок',
                'verbose_name_plural': 'Висновки',
                'ordering': ['created_at'],
            },
        ),
    ]
