# Generated by Django 6.0.4 on 2026-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0034_alter_doctorprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.TextField()),
                ('level', models.PositiveSmallIntegerField(default=4)),
                ('category_code', models.CharField(blank=True, max_length=10)),
                ('category_name', models.TextField(blank=True)),
                ('parent_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Код МКХ-10',
                'verbose_name_plural': 'Коди МКХ-10',
                'ordering': ['code'],
            },
        ),
    ]
