# Generated by Django 6.0.4 on 2026-09-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0035_icd10code'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconclusion',
            name='icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conclusions', to='diary.icd10code', verbose_name='Код МКХ-10'),
        ),
    ]
