# Generated by Django 6.0.4 on 2026-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0037_appointment_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='По батькові'),
        ),
    ]
