# Generated by Django 6.0.4 on 2026-10-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0038_userprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
