from .user_profile import UserProfile
from .healthRecord import HealthRecord
from .doctor_profile import DoctorProfile
from .question import Question
from .schedule import Schedule          
from .appointment import Appointment    
from .question_message import QuestionMessage 
from .medical_conclusion import MedicalConclusion
from .ICD10Code import ICD10Code